---
abstract: 'OO wrapper to gpc library (translated from Inline-based Math::Geometry::Planar::GPC::Polygon to XS) '
author:
  - 'Eric L. Wilhelm / transalted to XS by Alexei Kasatkin'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-Geometry-Planar-GPC-PolygonXS
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.052'
