---
abstract: 'OO wrapper to gpc library'
author:
  - 'Eric L. Wilhelm / transalted to XS by Alexei Kasatkin'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Geometry-Planar-GPC-PolygonXS
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.05
